/*
 * Tasques API
 *
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonVersion {
    #[serde(rename = "primary_term", skip_serializing_if = "Option::is_none")]
    pub primary_term: Option<i32>,
    #[serde(rename = "seq_num", skip_serializing_if = "Option::is_none")]
    pub seq_num: Option<i32>,
}

impl CommonVersion {
    pub fn new() -> CommonVersion {
        CommonVersion {
            primary_term: None,
            seq_num: None,
        }
    }
}
