/*
 * Tasques API
 *
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonBody {
    #[serde(rename = "message")]
    pub message: String,
}

impl CommonBody {
    pub fn new(message: String) -> CommonBody {
        CommonBody { message }
    }
}
