/*
 * Tasques API
 *
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskLastClaimed {
    #[serde(rename = "claimed_at")]
    pub claimed_at: String,
    #[serde(rename = "last_report", skip_serializing_if = "Option::is_none")]
    pub last_report: Option<crate::models::TaskReport>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<crate::models::TaskResult>,
    #[serde(rename = "times_out_at")]
    pub times_out_at: String,
    #[serde(rename = "worker_id")]
    pub worker_id: String,
}

impl TaskLastClaimed {
    pub fn new(claimed_at: String, times_out_at: String, worker_id: String) -> TaskLastClaimed {
        TaskLastClaimed {
            claimed_at,
            last_report: None,
            result: None,
            times_out_at,
            worker_id,
        }
    }
}
