/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CommonVersion
 */
public class CommonVersionTest {
    private final CommonVersion model = new CommonVersion();

    /**
     * Model tests for CommonVersion
     */
    @Test
    public void testCommonVersion() {
        // TODO: test CommonVersion
    }

    /**
     * Test the property 'primaryTerm'
     */
    @Test
    public void primaryTermTest() {
        // TODO: test primaryTerm
    }

    /**
     * Test the property 'seqNum'
     */
    @Test
    public void seqNumTest() {
        // TODO: test seqNum
    }

}
