/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskReportedData
 */
public class TaskReportedDataTest {
    private final TaskReportedData model = new TaskReportedData();

    /**
     * Model tests for TaskReportedData
     */
    @Test
    public void testTaskReportedData() {
        // TODO: test TaskReportedData
    }

}
