/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskClaim
 */
public class TaskClaimTest {
    private final TaskClaim model = new TaskClaim();

    /**
     * Model tests for TaskClaim
     */
    @Test
    public void testTaskClaim() {
        // TODO: test TaskClaim
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'blockFor'
     */
    @Test
    public void blockForTest() {
        // TODO: test blockFor
    }

    /**
     * Test the property 'queues'
     */
    @Test
    public void queuesTest() {
        // TODO: test queues
    }

}
