/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskArgs
 */
public class TaskArgsTest {
    private final TaskArgs model = new TaskArgs();

    /**
     * Model tests for TaskArgs
     */
    @Test
    public void testTaskArgs() {
        // TODO: test TaskArgs
    }

}
