/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import tasques.client.models.CommonMetadata;
import tasques.client.models.TaskLastClaimed;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskTask
 */
public class TaskTaskTest {
    private final TaskTask model = new TaskTask();

    /**
     * Model tests for TaskTask
     */
    @Test
    public void testTaskTask() {
        // TODO: test TaskTask
    }

    /**
     * Test the property 'args'
     */
    @Test
    public void argsTest() {
        // TODO: test args
    }

    /**
     * Test the property 'attempted'
     */
    @Test
    public void attemptedTest() {
        // TODO: test attempted
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'lastClaimed'
     */
    @Test
    public void lastClaimedTest() {
        // TODO: test lastClaimed
    }

    /**
     * Test the property 'lastEnqueuedAt'
     */
    @Test
    public void lastEnqueuedAtTest() {
        // TODO: test lastEnqueuedAt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'processingTimeout'
     */
    @Test
    public void processingTimeoutTest() {
        // TODO: test processingTimeout
    }

    /**
     * Test the property 'queue'
     */
    @Test
    public void queueTest() {
        // TODO: test queue
    }

    /**
     * Test the property 'retryTimes'
     */
    @Test
    public void retryTimesTest() {
        // TODO: test retryTimes
    }

    /**
     * Test the property 'runAt'
     */
    @Test
    public void runAtTest() {
        // TODO: test runAt
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

}
