/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskResult
 */
public class TaskResultTest {
    private final TaskResult model = new TaskResult();

    /**
     * Model tests for TaskResult
     */
    @Test
    public void testTaskResult() {
        // TODO: test TaskResult
    }

    /**
     * Test the property 'at'
     */
    @Test
    public void atTest() {
        // TODO: test at
    }

    /**
     * Test the property 'failure'
     */
    @Test
    public void failureTest() {
        // TODO: test failure
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

}
