/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import tasques.client.models.TaskReport;
import tasques.client.models.TaskResult;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskLastClaimed
 */
public class TaskLastClaimedTest {
    private final TaskLastClaimed model = new TaskLastClaimed();

    /**
     * Model tests for TaskLastClaimed
     */
    @Test
    public void testTaskLastClaimed() {
        // TODO: test TaskLastClaimed
    }

    /**
     * Test the property 'claimedAt'
     */
    @Test
    public void claimedAtTest() {
        // TODO: test claimedAt
    }

    /**
     * Test the property 'lastReport'
     */
    @Test
    public void lastReportTest() {
        // TODO: test lastReport
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'timesOutAt'
     */
    @Test
    public void timesOutAtTest() {
        // TODO: test timesOutAt
    }

    /**
     * Test the property 'workerId'
     */
    @Test
    public void workerIdTest() {
        // TODO: test workerId
    }

}
