/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CommonVersion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-10T20:22:14.162+09:00[Asia/Tokyo]")
public class CommonVersion {
  public static final String SERIALIZED_NAME_PRIMARY_TERM = "primary_term";
  @SerializedName(SERIALIZED_NAME_PRIMARY_TERM)
  private Integer primaryTerm;

  public static final String SERIALIZED_NAME_SEQ_NUM = "seq_num";
  @SerializedName(SERIALIZED_NAME_SEQ_NUM)
  private Integer seqNum;


  public CommonVersion primaryTerm(Integer primaryTerm) {
    
    this.primaryTerm = primaryTerm;
    return this;
  }

   /**
   * Get primaryTerm
   * @return primaryTerm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPrimaryTerm() {
    return primaryTerm;
  }


  public void setPrimaryTerm(Integer primaryTerm) {
    this.primaryTerm = primaryTerm;
  }


  public CommonVersion seqNum(Integer seqNum) {
    
    this.seqNum = seqNum;
    return this;
  }

   /**
   * Get seqNum
   * @return seqNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSeqNum() {
    return seqNum;
  }


  public void setSeqNum(Integer seqNum) {
    this.seqNum = seqNum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonVersion commonVersion = (CommonVersion) o;
    return Objects.equals(this.primaryTerm, commonVersion.primaryTerm) &&
        Objects.equals(this.seqNum, commonVersion.seqNum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primaryTerm, seqNum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonVersion {\n");
    sb.append("    primaryTerm: ").append(toIndentedString(primaryTerm)).append("\n");
    sb.append("    seqNum: ").append(toIndentedString(seqNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

