/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * TaskResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-10T20:22:14.162+09:00[Asia/Tokyo]")
public class TaskResult {
  public static final String SERIALIZED_NAME_AT = "at";
  @SerializedName(SERIALIZED_NAME_AT)
  private OffsetDateTime at;

  public static final String SERIALIZED_NAME_FAILURE = "failure";
  @SerializedName(SERIALIZED_NAME_FAILURE)
  private Object failure;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Object success;


  public TaskResult at(OffsetDateTime at) {
    
    this.at = at;
    return this;
  }

   /**
   * Get at
   * @return at
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getAt() {
    return at;
  }


  public void setAt(OffsetDateTime at) {
    this.at = at;
  }


  public TaskResult failure(Object failure) {
    
    this.failure = failure;
    return this;
  }

   /**
   * Results. Only one of the following will be filled in at a given time
   * @return failure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Results. Only one of the following will be filled in at a given time")

  public Object getFailure() {
    return failure;
  }


  public void setFailure(Object failure) {
    this.failure = failure;
  }


  public TaskResult success(Object success) {
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSuccess() {
    return success;
  }


  public void setSuccess(Object success) {
    this.success = success;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskResult taskResult = (TaskResult) o;
    return Objects.equals(this.at, taskResult.at) &&
        Objects.equals(this.failure, taskResult.failure) &&
        Objects.equals(this.success, taskResult.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(at, failure, success);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskResult {\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

