/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TaskClaim
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-10T20:22:14.162+09:00[Asia/Tokyo]")
public class TaskClaim {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Integer amount;

  public static final String SERIALIZED_NAME_BLOCK_FOR = "block_for";
  @SerializedName(SERIALIZED_NAME_BLOCK_FOR)
  private String blockFor;

  public static final String SERIALIZED_NAME_QUEUES = "queues";
  @SerializedName(SERIALIZED_NAME_QUEUES)
  private List<String> queues = new ArrayList<String>();


  public TaskClaim amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Integer getAmount() {
    return amount;
  }


  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public TaskClaim blockFor(String blockFor) {
    
    this.blockFor = blockFor;
    return this;
  }

   /**
   * Get blockFor
   * @return blockFor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1s", value = "")

  public String getBlockFor() {
    return blockFor;
  }


  public void setBlockFor(String blockFor) {
    this.blockFor = blockFor;
  }


  public TaskClaim queues(List<String> queues) {
    
    this.queues = queues;
    return this;
  }

  public TaskClaim addQueuesItem(String queuesItem) {
    this.queues.add(queuesItem);
    return this;
  }

   /**
   * Get queues
   * @return queues
  **/
  @ApiModelProperty(example = "[run-later, resize-images]", required = true, value = "")

  public List<String> getQueues() {
    return queues;
  }


  public void setQueues(List<String> queues) {
    this.queues = queues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskClaim taskClaim = (TaskClaim) o;
    return Objects.equals(this.amount, taskClaim.amount) &&
        Objects.equals(this.blockFor, taskClaim.blockFor) &&
        Objects.equals(this.queues, taskClaim.queues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, blockFor, queues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskClaim {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    blockFor: ").append(toIndentedString(blockFor)).append("\n");
    sb.append("    queues: ").append(toIndentedString(queues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

