/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import tasques.client.models.TaskReport;
import tasques.client.models.TaskResult;

/**
 * TaskLastClaimed
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-10T20:22:14.162+09:00[Asia/Tokyo]")
public class TaskLastClaimed {
  public static final String SERIALIZED_NAME_CLAIMED_AT = "claimed_at";
  @SerializedName(SERIALIZED_NAME_CLAIMED_AT)
  private OffsetDateTime claimedAt;

  public static final String SERIALIZED_NAME_LAST_REPORT = "last_report";
  @SerializedName(SERIALIZED_NAME_LAST_REPORT)
  private TaskReport lastReport;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private TaskResult result;

  public static final String SERIALIZED_NAME_TIMES_OUT_AT = "times_out_at";
  @SerializedName(SERIALIZED_NAME_TIMES_OUT_AT)
  private OffsetDateTime timesOutAt;

  public static final String SERIALIZED_NAME_WORKER_ID = "worker_id";
  @SerializedName(SERIALIZED_NAME_WORKER_ID)
  private String workerId;


  public TaskLastClaimed claimedAt(OffsetDateTime claimedAt) {
    
    this.claimedAt = claimedAt;
    return this;
  }

   /**
   * Get claimedAt
   * @return claimedAt
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getClaimedAt() {
    return claimedAt;
  }


  public void setClaimedAt(OffsetDateTime claimedAt) {
    this.claimedAt = claimedAt;
  }


  public TaskLastClaimed lastReport(TaskReport lastReport) {
    
    this.lastReport = lastReport;
    return this;
  }

   /**
   * Get lastReport
   * @return lastReport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TaskReport getLastReport() {
    return lastReport;
  }


  public void setLastReport(TaskReport lastReport) {
    this.lastReport = lastReport;
  }


  public TaskLastClaimed result(TaskResult result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TaskResult getResult() {
    return result;
  }


  public void setResult(TaskResult result) {
    this.result = result;
  }


  public TaskLastClaimed timesOutAt(OffsetDateTime timesOutAt) {
    
    this.timesOutAt = timesOutAt;
    return this;
  }

   /**
   * Get timesOutAt
   * @return timesOutAt
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getTimesOutAt() {
    return timesOutAt;
  }


  public void setTimesOutAt(OffsetDateTime timesOutAt) {
    this.timesOutAt = timesOutAt;
  }


  public TaskLastClaimed workerId(String workerId) {
    
    this.workerId = workerId;
    return this;
  }

   /**
   * Get workerId
   * @return workerId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getWorkerId() {
    return workerId;
  }


  public void setWorkerId(String workerId) {
    this.workerId = workerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskLastClaimed taskLastClaimed = (TaskLastClaimed) o;
    return Objects.equals(this.claimedAt, taskLastClaimed.claimedAt) &&
        Objects.equals(this.lastReport, taskLastClaimed.lastReport) &&
        Objects.equals(this.result, taskLastClaimed.result) &&
        Objects.equals(this.timesOutAt, taskLastClaimed.timesOutAt) &&
        Objects.equals(this.workerId, taskLastClaimed.workerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimedAt, lastReport, result, timesOutAt, workerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskLastClaimed {\n");
    sb.append("    claimedAt: ").append(toIndentedString(claimedAt)).append("\n");
    sb.append("    lastReport: ").append(toIndentedString(lastReport)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    timesOutAt: ").append(toIndentedString(timesOutAt)).append("\n");
    sb.append("    workerId: ").append(toIndentedString(workerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

