/*
 * Tasques API
 * A Task queue backed by Elasticsearch
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tasques.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import tasques.client.models.CommonMetadata;
import tasques.client.models.TaskLastClaimed;

/**
 * TaskTask
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-10T20:22:14.162+09:00[Asia/Tokyo]")
public class TaskTask {
  public static final String SERIALIZED_NAME_ARGS = "args";
  @SerializedName(SERIALIZED_NAME_ARGS)
  private Object args;

  public static final String SERIALIZED_NAME_ATTEMPTED = "attempted";
  @SerializedName(SERIALIZED_NAME_ATTEMPTED)
  private Integer attempted;

  public static final String SERIALIZED_NAME_CONTEXT = "context";
  @SerializedName(SERIALIZED_NAME_CONTEXT)
  private Object context;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_LAST_CLAIMED = "last_claimed";
  @SerializedName(SERIALIZED_NAME_LAST_CLAIMED)
  private TaskLastClaimed lastClaimed;

  public static final String SERIALIZED_NAME_LAST_ENQUEUED_AT = "last_enqueued_at";
  @SerializedName(SERIALIZED_NAME_LAST_ENQUEUED_AT)
  private OffsetDateTime lastEnqueuedAt;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private CommonMetadata metadata;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  public static final String SERIALIZED_NAME_PROCESSING_TIMEOUT = "processing_timeout";
  @SerializedName(SERIALIZED_NAME_PROCESSING_TIMEOUT)
  private String processingTimeout;

  public static final String SERIALIZED_NAME_QUEUE = "queue";
  @SerializedName(SERIALIZED_NAME_QUEUE)
  private String queue;

  public static final String SERIALIZED_NAME_RETRY_TIMES = "retry_times";
  @SerializedName(SERIALIZED_NAME_RETRY_TIMES)
  private Integer retryTimes;

  public static final String SERIALIZED_NAME_RUN_AT = "run_at";
  @SerializedName(SERIALIZED_NAME_RUN_AT)
  private OffsetDateTime runAt;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;


  public TaskTask args(Object args) {
    
    this.args = args;
    return this;
  }

   /**
   * Get args
   * @return args
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getArgs() {
    return args;
  }


  public void setArgs(Object args) {
    this.args = args;
  }


  public TaskTask attempted(Integer attempted) {
    
    this.attempted = attempted;
    return this;
  }

   /**
   * Get attempted
   * @return attempted
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getAttempted() {
    return attempted;
  }


  public void setAttempted(Integer attempted) {
    this.attempted = attempted;
  }


  public TaskTask context(Object context) {
    
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getContext() {
    return context;
  }


  public void setContext(Object context) {
    this.context = context;
  }


  public TaskTask id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public TaskTask kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(example = "sayHello", required = true, value = "")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public TaskTask lastClaimed(TaskLastClaimed lastClaimed) {
    
    this.lastClaimed = lastClaimed;
    return this;
  }

   /**
   * Get lastClaimed
   * @return lastClaimed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TaskLastClaimed getLastClaimed() {
    return lastClaimed;
  }


  public void setLastClaimed(TaskLastClaimed lastClaimed) {
    this.lastClaimed = lastClaimed;
  }


  public TaskTask lastEnqueuedAt(OffsetDateTime lastEnqueuedAt) {
    
    this.lastEnqueuedAt = lastEnqueuedAt;
    return this;
  }

   /**
   * Get lastEnqueuedAt
   * @return lastEnqueuedAt
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getLastEnqueuedAt() {
    return lastEnqueuedAt;
  }


  public void setLastEnqueuedAt(OffsetDateTime lastEnqueuedAt) {
    this.lastEnqueuedAt = lastEnqueuedAt;
  }


  public TaskTask metadata(CommonMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(required = true, value = "")

  public CommonMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(CommonMetadata metadata) {
    this.metadata = metadata;
  }


  public TaskTask priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getPriority() {
    return priority;
  }


  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public TaskTask processingTimeout(String processingTimeout) {
    
    this.processingTimeout = processingTimeout;
    return this;
  }

   /**
   * Get processingTimeout
   * @return processingTimeout
  **/
  @ApiModelProperty(example = "30m", required = true, value = "")

  public String getProcessingTimeout() {
    return processingTimeout;
  }


  public void setProcessingTimeout(String processingTimeout) {
    this.processingTimeout = processingTimeout;
  }


  public TaskTask queue(String queue) {
    
    this.queue = queue;
    return this;
  }

   /**
   * Get queue
   * @return queue
  **/
  @ApiModelProperty(example = "run-later", required = true, value = "")

  public String getQueue() {
    return queue;
  }


  public void setQueue(String queue) {
    this.queue = queue;
  }


  public TaskTask retryTimes(Integer retryTimes) {
    
    this.retryTimes = retryTimes;
    return this;
  }

   /**
   * Get retryTimes
   * @return retryTimes
  **/
  @ApiModelProperty(example = "10", required = true, value = "")

  public Integer getRetryTimes() {
    return retryTimes;
  }


  public void setRetryTimes(Integer retryTimes) {
    this.retryTimes = retryTimes;
  }


  public TaskTask runAt(OffsetDateTime runAt) {
    
    this.runAt = runAt;
    return this;
  }

   /**
   * Get runAt
   * @return runAt
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getRunAt() {
    return runAt;
  }


  public void setRunAt(OffsetDateTime runAt) {
    this.runAt = runAt;
  }


  public TaskTask state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "queued", required = true, value = "")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskTask taskTask = (TaskTask) o;
    return Objects.equals(this.args, taskTask.args) &&
        Objects.equals(this.attempted, taskTask.attempted) &&
        Objects.equals(this.context, taskTask.context) &&
        Objects.equals(this.id, taskTask.id) &&
        Objects.equals(this.kind, taskTask.kind) &&
        Objects.equals(this.lastClaimed, taskTask.lastClaimed) &&
        Objects.equals(this.lastEnqueuedAt, taskTask.lastEnqueuedAt) &&
        Objects.equals(this.metadata, taskTask.metadata) &&
        Objects.equals(this.priority, taskTask.priority) &&
        Objects.equals(this.processingTimeout, taskTask.processingTimeout) &&
        Objects.equals(this.queue, taskTask.queue) &&
        Objects.equals(this.retryTimes, taskTask.retryTimes) &&
        Objects.equals(this.runAt, taskTask.runAt) &&
        Objects.equals(this.state, taskTask.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, attempted, context, id, kind, lastClaimed, lastEnqueuedAt, metadata, priority, processingTimeout, queue, retryTimes, runAt, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskTask {\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    attempted: ").append(toIndentedString(attempted)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    lastClaimed: ").append(toIndentedString(lastClaimed)).append("\n");
    sb.append("    lastEnqueuedAt: ").append(toIndentedString(lastEnqueuedAt)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    processingTimeout: ").append(toIndentedString(processingTimeout)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    retryTimes: ").append(toIndentedString(retryTimes)).append("\n");
    sb.append("    runAt: ").append(toIndentedString(runAt)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

