// Code generated by go-swagger; DO NOT EDIT.

package recurring_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExistingRecurringTaskParams creates a new GetExistingRecurringTaskParams object
// with the default values initialized.
func NewGetExistingRecurringTaskParams() *GetExistingRecurringTaskParams {
	var ()
	return &GetExistingRecurringTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExistingRecurringTaskParamsWithTimeout creates a new GetExistingRecurringTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExistingRecurringTaskParamsWithTimeout(timeout time.Duration) *GetExistingRecurringTaskParams {
	var ()
	return &GetExistingRecurringTaskParams{

		timeout: timeout,
	}
}

// NewGetExistingRecurringTaskParamsWithContext creates a new GetExistingRecurringTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExistingRecurringTaskParamsWithContext(ctx context.Context) *GetExistingRecurringTaskParams {
	var ()
	return &GetExistingRecurringTaskParams{

		Context: ctx,
	}
}

// NewGetExistingRecurringTaskParamsWithHTTPClient creates a new GetExistingRecurringTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExistingRecurringTaskParamsWithHTTPClient(client *http.Client) *GetExistingRecurringTaskParams {
	var ()
	return &GetExistingRecurringTaskParams{
		HTTPClient: client,
	}
}

/*GetExistingRecurringTaskParams contains all the parameters to send to the API endpoint
for the get existing recurring task operation typically these are written to a http.Request
*/
type GetExistingRecurringTaskParams struct {

	/*ID
	  The id of the Recurring Task

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) WithTimeout(timeout time.Duration) *GetExistingRecurringTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) WithContext(ctx context.Context) *GetExistingRecurringTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) WithHTTPClient(client *http.Client) *GetExistingRecurringTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) WithID(id string) *GetExistingRecurringTaskParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get existing recurring task params
func (o *GetExistingRecurringTaskParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetExistingRecurringTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
