// Code generated by go-swagger; DO NOT EDIT.

package recurring_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListExistingRecurringTasksParams creates a new ListExistingRecurringTasksParams object
// with the default values initialized.
func NewListExistingRecurringTasksParams() *ListExistingRecurringTasksParams {

	return &ListExistingRecurringTasksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListExistingRecurringTasksParamsWithTimeout creates a new ListExistingRecurringTasksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListExistingRecurringTasksParamsWithTimeout(timeout time.Duration) *ListExistingRecurringTasksParams {

	return &ListExistingRecurringTasksParams{

		timeout: timeout,
	}
}

// NewListExistingRecurringTasksParamsWithContext creates a new ListExistingRecurringTasksParams object
// with the default values initialized, and the ability to set a context for a request
func NewListExistingRecurringTasksParamsWithContext(ctx context.Context) *ListExistingRecurringTasksParams {

	return &ListExistingRecurringTasksParams{

		Context: ctx,
	}
}

// NewListExistingRecurringTasksParamsWithHTTPClient creates a new ListExistingRecurringTasksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListExistingRecurringTasksParamsWithHTTPClient(client *http.Client) *ListExistingRecurringTasksParams {

	return &ListExistingRecurringTasksParams{
		HTTPClient: client,
	}
}

/*ListExistingRecurringTasksParams contains all the parameters to send to the API endpoint
for the list existing recurring tasks operation typically these are written to a http.Request
*/
type ListExistingRecurringTasksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list existing recurring tasks params
func (o *ListExistingRecurringTasksParams) WithTimeout(timeout time.Duration) *ListExistingRecurringTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list existing recurring tasks params
func (o *ListExistingRecurringTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list existing recurring tasks params
func (o *ListExistingRecurringTasksParams) WithContext(ctx context.Context) *ListExistingRecurringTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list existing recurring tasks params
func (o *ListExistingRecurringTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list existing recurring tasks params
func (o *ListExistingRecurringTasksParams) WithHTTPClient(client *http.Client) *ListExistingRecurringTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list existing recurring tasks params
func (o *ListExistingRecurringTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListExistingRecurringTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
