// Code generated by go-swagger; DO NOT EDIT.

package recurring_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/lloydmeta/tasques/models"
)

// NewUpdateExistingRecurringTaskParams creates a new UpdateExistingRecurringTaskParams object
// with the default values initialized.
func NewUpdateExistingRecurringTaskParams() *UpdateExistingRecurringTaskParams {
	var ()
	return &UpdateExistingRecurringTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateExistingRecurringTaskParamsWithTimeout creates a new UpdateExistingRecurringTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateExistingRecurringTaskParamsWithTimeout(timeout time.Duration) *UpdateExistingRecurringTaskParams {
	var ()
	return &UpdateExistingRecurringTaskParams{

		timeout: timeout,
	}
}

// NewUpdateExistingRecurringTaskParamsWithContext creates a new UpdateExistingRecurringTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateExistingRecurringTaskParamsWithContext(ctx context.Context) *UpdateExistingRecurringTaskParams {
	var ()
	return &UpdateExistingRecurringTaskParams{

		Context: ctx,
	}
}

// NewUpdateExistingRecurringTaskParamsWithHTTPClient creates a new UpdateExistingRecurringTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateExistingRecurringTaskParamsWithHTTPClient(client *http.Client) *UpdateExistingRecurringTaskParams {
	var ()
	return &UpdateExistingRecurringTaskParams{
		HTTPClient: client,
	}
}

/*UpdateExistingRecurringTaskParams contains all the parameters to send to the API endpoint
for the update existing recurring task operation typically these are written to a http.Request
*/
type UpdateExistingRecurringTaskParams struct {

	/*ID
	  The id of the Recurring Task

	*/
	ID string
	/*RecurringTaskUpdate
	  The request body

	*/
	RecurringTaskUpdate *models.RecurringTaskUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) WithTimeout(timeout time.Duration) *UpdateExistingRecurringTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) WithContext(ctx context.Context) *UpdateExistingRecurringTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) WithHTTPClient(client *http.Client) *UpdateExistingRecurringTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) WithID(id string) *UpdateExistingRecurringTaskParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) SetID(id string) {
	o.ID = id
}

// WithRecurringTaskUpdate adds the recurringTaskUpdate to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) WithRecurringTaskUpdate(recurringTaskUpdate *models.RecurringTaskUpdate) *UpdateExistingRecurringTaskParams {
	o.SetRecurringTaskUpdate(recurringTaskUpdate)
	return o
}

// SetRecurringTaskUpdate adds the recurringTaskUpdate to the update existing recurring task params
func (o *UpdateExistingRecurringTaskParams) SetRecurringTaskUpdate(recurringTaskUpdate *models.RecurringTaskUpdate) {
	o.RecurringTaskUpdate = recurringTaskUpdate
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateExistingRecurringTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.RecurringTaskUpdate != nil {
		if err := r.SetBodyParam(o.RecurringTaskUpdate); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
