// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/lloydmeta/tasques/models"
)

// ClaimTasksReader is a Reader for the ClaimTasks structure.
type ClaimTasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClaimTasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClaimTasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewClaimTasksOK creates a ClaimTasksOK with default headers values
func NewClaimTasksOK() *ClaimTasksOK {
	return &ClaimTasksOK{}
}

/*ClaimTasksOK handles this case with default header values.

OK
*/
type ClaimTasksOK struct {
	Payload []*models.TaskTask
}

func (o *ClaimTasksOK) Error() string {
	return fmt.Sprintf("[POST /tasques/claims][%d] claimTasksOK  %+v", 200, o.Payload)
}

func (o *ClaimTasksOK) GetPayload() []*models.TaskTask {
	return o.Payload
}

func (o *ClaimTasksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
