// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExistingTaskParams creates a new GetExistingTaskParams object
// with the default values initialized.
func NewGetExistingTaskParams() *GetExistingTaskParams {
	var ()
	return &GetExistingTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExistingTaskParamsWithTimeout creates a new GetExistingTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExistingTaskParamsWithTimeout(timeout time.Duration) *GetExistingTaskParams {
	var ()
	return &GetExistingTaskParams{

		timeout: timeout,
	}
}

// NewGetExistingTaskParamsWithContext creates a new GetExistingTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExistingTaskParamsWithContext(ctx context.Context) *GetExistingTaskParams {
	var ()
	return &GetExistingTaskParams{

		Context: ctx,
	}
}

// NewGetExistingTaskParamsWithHTTPClient creates a new GetExistingTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExistingTaskParamsWithHTTPClient(client *http.Client) *GetExistingTaskParams {
	var ()
	return &GetExistingTaskParams{
		HTTPClient: client,
	}
}

/*GetExistingTaskParams contains all the parameters to send to the API endpoint
for the get existing task operation typically these are written to a http.Request
*/
type GetExistingTaskParams struct {

	/*ID
	  The id of the Task

	*/
	ID string
	/*Queue
	  The Queue of the Task

	*/
	Queue string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get existing task params
func (o *GetExistingTaskParams) WithTimeout(timeout time.Duration) *GetExistingTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get existing task params
func (o *GetExistingTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get existing task params
func (o *GetExistingTaskParams) WithContext(ctx context.Context) *GetExistingTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get existing task params
func (o *GetExistingTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get existing task params
func (o *GetExistingTaskParams) WithHTTPClient(client *http.Client) *GetExistingTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get existing task params
func (o *GetExistingTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get existing task params
func (o *GetExistingTaskParams) WithID(id string) *GetExistingTaskParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get existing task params
func (o *GetExistingTaskParams) SetID(id string) {
	o.ID = id
}

// WithQueue adds the queue to the get existing task params
func (o *GetExistingTaskParams) WithQueue(queue string) *GetExistingTaskParams {
	o.SetQueue(queue)
	return o
}

// SetQueue adds the queue to the get existing task params
func (o *GetExistingTaskParams) SetQueue(queue string) {
	o.Queue = queue
}

// WriteToRequest writes these params to a swagger request
func (o *GetExistingTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param queue
	if err := r.SetPathParam("queue", o.Queue); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
