// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/lloydmeta/tasques/models"
)

// GetExistingTaskReader is a Reader for the GetExistingTask structure.
type GetExistingTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExistingTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExistingTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetExistingTaskNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetExistingTaskOK creates a GetExistingTaskOK with default headers values
func NewGetExistingTaskOK() *GetExistingTaskOK {
	return &GetExistingTaskOK{}
}

/*GetExistingTaskOK handles this case with default header values.

OK
*/
type GetExistingTaskOK struct {
	Payload *models.TaskTask
}

func (o *GetExistingTaskOK) Error() string {
	return fmt.Sprintf("[GET /tasques/{queue}/{id}][%d] getExistingTaskOK  %+v", 200, o.Payload)
}

func (o *GetExistingTaskOK) GetPayload() *models.TaskTask {
	return o.Payload
}

func (o *GetExistingTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetExistingTaskNotFound creates a GetExistingTaskNotFound with default headers values
func NewGetExistingTaskNotFound() *GetExistingTaskNotFound {
	return &GetExistingTaskNotFound{}
}

/*GetExistingTaskNotFound handles this case with default header values.

Task does not exist
*/
type GetExistingTaskNotFound struct {
	Payload *models.CommonBody
}

func (o *GetExistingTaskNotFound) Error() string {
	return fmt.Sprintf("[GET /tasques/{queue}/{id}][%d] getExistingTaskNotFound  %+v", 404, o.Payload)
}

func (o *GetExistingTaskNotFound) GetPayload() *models.CommonBody {
	return o.Payload
}

func (o *GetExistingTaskNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
