// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/lloydmeta/tasques/models"
)

// NewMarkClaimedTaskDoneParams creates a new MarkClaimedTaskDoneParams object
// with the default values initialized.
func NewMarkClaimedTaskDoneParams() *MarkClaimedTaskDoneParams {
	var ()
	return &MarkClaimedTaskDoneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMarkClaimedTaskDoneParamsWithTimeout creates a new MarkClaimedTaskDoneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMarkClaimedTaskDoneParamsWithTimeout(timeout time.Duration) *MarkClaimedTaskDoneParams {
	var ()
	return &MarkClaimedTaskDoneParams{

		timeout: timeout,
	}
}

// NewMarkClaimedTaskDoneParamsWithContext creates a new MarkClaimedTaskDoneParams object
// with the default values initialized, and the ability to set a context for a request
func NewMarkClaimedTaskDoneParamsWithContext(ctx context.Context) *MarkClaimedTaskDoneParams {
	var ()
	return &MarkClaimedTaskDoneParams{

		Context: ctx,
	}
}

// NewMarkClaimedTaskDoneParamsWithHTTPClient creates a new MarkClaimedTaskDoneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMarkClaimedTaskDoneParamsWithHTTPClient(client *http.Client) *MarkClaimedTaskDoneParams {
	var ()
	return &MarkClaimedTaskDoneParams{
		HTTPClient: client,
	}
}

/*MarkClaimedTaskDoneParams contains all the parameters to send to the API endpoint
for the mark claimed task done operation typically these are written to a http.Request
*/
type MarkClaimedTaskDoneParams struct {

	/*XTASQUESWORKERID
	  Worker ID

	*/
	XTASQUESWORKERID string
	/*ID
	  The id of the Task

	*/
	ID string
	/*Queue
	  The Queue of the Task

	*/
	Queue string
	/*Success
	  The request body

	*/
	Success *models.TaskSuccess

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithTimeout(timeout time.Duration) *MarkClaimedTaskDoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithContext(ctx context.Context) *MarkClaimedTaskDoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithHTTPClient(client *http.Client) *MarkClaimedTaskDoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXTASQUESWORKERID adds the xTASQUESWORKERID to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithXTASQUESWORKERID(xTASQUESWORKERID string) *MarkClaimedTaskDoneParams {
	o.SetXTASQUESWORKERID(xTASQUESWORKERID)
	return o
}

// SetXTASQUESWORKERID adds the xTASQUESWORKERId to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetXTASQUESWORKERID(xTASQUESWORKERID string) {
	o.XTASQUESWORKERID = xTASQUESWORKERID
}

// WithID adds the id to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithID(id string) *MarkClaimedTaskDoneParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetID(id string) {
	o.ID = id
}

// WithQueue adds the queue to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithQueue(queue string) *MarkClaimedTaskDoneParams {
	o.SetQueue(queue)
	return o
}

// SetQueue adds the queue to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetQueue(queue string) {
	o.Queue = queue
}

// WithSuccess adds the success to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) WithSuccess(success *models.TaskSuccess) *MarkClaimedTaskDoneParams {
	o.SetSuccess(success)
	return o
}

// SetSuccess adds the success to the mark claimed task done params
func (o *MarkClaimedTaskDoneParams) SetSuccess(success *models.TaskSuccess) {
	o.Success = success
}

// WriteToRequest writes these params to a swagger request
func (o *MarkClaimedTaskDoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-TASQUES-WORKER-ID
	if err := r.SetHeaderParam("X-TASQUES-WORKER-ID", o.XTASQUESWORKERID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param queue
	if err := r.SetPathParam("queue", o.Queue); err != nil {
		return err
	}

	if o.Success != nil {
		if err := r.SetBodyParam(o.Success); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
