// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnclaimExistingTaskParams creates a new UnclaimExistingTaskParams object
// with the default values initialized.
func NewUnclaimExistingTaskParams() *UnclaimExistingTaskParams {
	var ()
	return &UnclaimExistingTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnclaimExistingTaskParamsWithTimeout creates a new UnclaimExistingTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnclaimExistingTaskParamsWithTimeout(timeout time.Duration) *UnclaimExistingTaskParams {
	var ()
	return &UnclaimExistingTaskParams{

		timeout: timeout,
	}
}

// NewUnclaimExistingTaskParamsWithContext creates a new UnclaimExistingTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnclaimExistingTaskParamsWithContext(ctx context.Context) *UnclaimExistingTaskParams {
	var ()
	return &UnclaimExistingTaskParams{

		Context: ctx,
	}
}

// NewUnclaimExistingTaskParamsWithHTTPClient creates a new UnclaimExistingTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnclaimExistingTaskParamsWithHTTPClient(client *http.Client) *UnclaimExistingTaskParams {
	var ()
	return &UnclaimExistingTaskParams{
		HTTPClient: client,
	}
}

/*UnclaimExistingTaskParams contains all the parameters to send to the API endpoint
for the unclaim existing task operation typically these are written to a http.Request
*/
type UnclaimExistingTaskParams struct {

	/*XTASQUESWORKERID
	  Worker ID

	*/
	XTASQUESWORKERID string
	/*ID
	  The id of the Task

	*/
	ID string
	/*Queue
	  The Queue of the Task

	*/
	Queue string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unclaim existing task params
func (o *UnclaimExistingTaskParams) WithTimeout(timeout time.Duration) *UnclaimExistingTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unclaim existing task params
func (o *UnclaimExistingTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unclaim existing task params
func (o *UnclaimExistingTaskParams) WithContext(ctx context.Context) *UnclaimExistingTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unclaim existing task params
func (o *UnclaimExistingTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unclaim existing task params
func (o *UnclaimExistingTaskParams) WithHTTPClient(client *http.Client) *UnclaimExistingTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unclaim existing task params
func (o *UnclaimExistingTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXTASQUESWORKERID adds the xTASQUESWORKERID to the unclaim existing task params
func (o *UnclaimExistingTaskParams) WithXTASQUESWORKERID(xTASQUESWORKERID string) *UnclaimExistingTaskParams {
	o.SetXTASQUESWORKERID(xTASQUESWORKERID)
	return o
}

// SetXTASQUESWORKERID adds the xTASQUESWORKERId to the unclaim existing task params
func (o *UnclaimExistingTaskParams) SetXTASQUESWORKERID(xTASQUESWORKERID string) {
	o.XTASQUESWORKERID = xTASQUESWORKERID
}

// WithID adds the id to the unclaim existing task params
func (o *UnclaimExistingTaskParams) WithID(id string) *UnclaimExistingTaskParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the unclaim existing task params
func (o *UnclaimExistingTaskParams) SetID(id string) {
	o.ID = id
}

// WithQueue adds the queue to the unclaim existing task params
func (o *UnclaimExistingTaskParams) WithQueue(queue string) *UnclaimExistingTaskParams {
	o.SetQueue(queue)
	return o
}

// SetQueue adds the queue to the unclaim existing task params
func (o *UnclaimExistingTaskParams) SetQueue(queue string) {
	o.Queue = queue
}

// WriteToRequest writes these params to a swagger request
func (o *UnclaimExistingTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-TASQUES-WORKER-ID
	if err := r.SetHeaderParam("X-TASQUES-WORKER-ID", o.XTASQUESWORKERID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param queue
	if err := r.SetPathParam("queue", o.Queue); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
