#!/usr/bin/env bash

cd "$(dirname "$0")"

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/recurring_tasques)" != "200" ]]; do
  echo "Waiting for Tasques server to come online ..."
  sleep 5;
done

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9201)" != "200" ]]; do
  echo "Waiting for Cipher ES server to come online ..."
  sleep 5;
done

go run main.go