apiVersion: v1
kind: Service
metadata:
  name: tasques
spec:
  selector:
    app: tasques
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasques
spec:
  selector:
    matchLabels:
      app: tasques
  replicas: 1
  template:
    metadata:
      labels:
        app: tasques
    spec:
      initContainers:
      - name: init-es
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -q --spider http://tasques-es-http:9200; do echo waiting for tasques-es-http; sleep 2; done;']
      - name: init-kb
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -q --spider http://tasques-kb-http:5601; do echo waiting for tasques-kb-http; sleep 2; done;']
      - name: init-apm
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -q --spider http://tasques-apm-http:8200; do echo waiting for tasques-apm-http; sleep 2; done;']
      - name: tasques-setup
        image: "lloydmeta/tasques:latest"
        command: ["/app/bin/tasques", "setup"]
        env:
        - name: GIN_MODE
          value: release
        - name: TASQUES_SERVER_BIND_ADDRESS
          value: 0.0.0.0:8080
        - name: TASQUES_SERVER_AUTH
          value: null
        - name: TASQUES_SERVER_ELASTICSEARCH_ADDRESSES
          value: http://tasques-es-http:9200
        - name: TASQUES_SERVER_ELASTICSEARCH_USER
          value: null
        - name: TASQUES_SERVER_KIBANA_ADDRESS
          value: http://tasques-kb-http:5601
        - name: TASQUES_SERVER_KIBANA_USER_NAME
          value: elastic
        - name: TASQUES_SERVER_KIBANA_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasques-es-elastic-user
              key: elastic
        - name: TASQUES_SERVER_APM_ADDRESS
          value: http://tasques-apm-http:8200
        - name: TASQUES_SERVER_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: tasques-apm-token
              key: secret-token
        - name: TASQUES_SERVER_LOGGING
          value: null
        - name: TASQUES_SERVER_LOGGING_LEVEL
          value: debug
      containers:
      - name: tasques
        image: "lloydmeta/tasques:latest"
        env:
        - name: GIN_MODE
          value: release
        - name: TASQUES_SERVER_BIND_ADDRESS
          value: 0.0.0.0:8080
        - name: TASQUES_SERVER_AUTH
          value: null
        - name: TASQUES_SERVER_ELASTICSEARCH_ADDRESSES
          value: http://tasques-es-http:9200
        - name: TASQUES_SERVER_ELASTICSEARCH_USER
          value: null
        - name: TASQUES_SERVER_KIBANA_ADDRESS
          value: http://tasques-kb-http:5601
        - name: TASQUES_SERVER_KIBANA_USER_NAME
          value: elastic
        - name: TASQUES_SERVER_KIBANA_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasques-es-elastic-user
              key: elastic
        - name: TASQUES_SERVER_APM_ADDRESS
          value: http://tasques-apm-http:8200
        - name: TASQUES_SERVER_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: tasques-apm-token
              key: secret-token
        - name: TASQUES_SERVER_LOGGING
          value: null
        - name: TASQUES_SERVER_LOGGING_LEVEL
          value: info