// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RecurringNewTask recurring new task
// swagger:model recurring.NewTask
type RecurringNewTask struct {

	// User-definable Id for the recurring Task. Must not collide with other existing ones.
	// Required: true
	ID *string `json:"id"`

	// A schedule expression; can be any valid cron expression, with some support for simple macros
	// Required: true
	ScheduleExpression *string `json:"schedule_expression"`

	// The Task to insert at intervals defined by ScheduleExpression
	// Required: true
	TaskDefinition *RecurringTaskDefinition `json:"task_definition"`
}

// Validate validates this recurring new task
func (m *RecurringNewTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheduleExpression(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskDefinition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecurringNewTask) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *RecurringNewTask) validateScheduleExpression(formats strfmt.Registry) error {

	if err := validate.Required("schedule_expression", "body", m.ScheduleExpression); err != nil {
		return err
	}

	return nil
}

func (m *RecurringNewTask) validateTaskDefinition(formats strfmt.Registry) error {

	if err := validate.Required("task_definition", "body", m.TaskDefinition); err != nil {
		return err
	}

	if m.TaskDefinition != nil {
		if err := m.TaskDefinition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("task_definition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecurringNewTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecurringNewTask) UnmarshalBinary(b []byte) error {
	var res RecurringNewTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
